image: docker:20.10.16
services:
  - docker:20.10.8-dind


variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay
    APP_IMAGE: caelumpirata/edge:june8 
    



stages:
    - build
    - test
    - docker
    - deploy

before_script:
  - chmod +x mvnw
  
maven-build:
    image: maven:3.8.5-openjdk-17
    stage: build
    script: "./mvnw clean package -Pproduction -e"
    artifacts:
        paths:
        - target/*.jar

maven-test:
    image: maven:3.8.5-openjdk-17
    stage: test
    script: "mvn test"
    artifacts:
        paths:
        - target/*.jar

docker-build:
    stage: docker
    image: docker:20.10.16
    services:
      - docker:20.10.8-dind
    variables:
        DOCKER_TLS_CERTDIR: ""
    before_script:  
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    script:
    - docker build -t $APP_IMAGE .
    - docker push $APP_IMAGE

# deploy:
#     stage: deploy
#     before_script:
#         - chmod 400 $SSH_KEY 
#     script:
#       - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@65.2.150.79 "
#         docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
#         docker run -d -p 9090:9090 $IMAGE_NAME:$IMAGE_TAG"


